### ISSUE TITLE
present is not included

### ISSUE THREAD

**Issue by reapsonex** [Stekeblad/Stekeblads-Video-Uploader#1]
I do not have anything add add present
java 9 and developer kit 9 install

**Comment by Stekeblad** [comment]
I am not sure what your problem is, I tried running the latest release with java 9 and it does not seem to be different from java 8. I also tried building the code with JDK 9 but I got several warnings that I will not look into right now.

To add a preset you open the settings window and write a name for your preset in the text field next to the "Add New Preset" button and then click said button. After that it should appear a new preset below that you can edit. Do not forget to click the save button before closing the settings window.

**Comment by reapsonex** [comment]
Clicking on the button does not work on my computer I have installed jdk 9, serverda tried my problem did not.

**Comment by Stekeblad** [comment]
It is possible to build from source code, but if you do that you need to get your own YouTube API key and use it

**Comment by reapsonex** [comment]
Sorry. I tried Java and jdk versions.

**Comment by Stekeblad** [comment]
I have no problems with creating presets using release 1.0 and java 8.
There is not much I can do without more details.

Please explain in detail step by step what you do, what you expect to happen and what actually happens

**Comment by Stekeblad** [comment]
Sorry but my Skype is private.
Can you try following what I do [in my introduction video](https://youtu.be/Nohm6EEJ0jo)? If it does not work when you follow the video, at what time in the video is it and what happens for you instead?

**Comment by reapsonex** [comment]
"ADD NEW PRESENT" click on the button but I have to add it normally but I can not do it.

**Comment by Stekeblad** [comment]
If you follow the steps in the image below in order 1, 2, 3 it should work. It sounds like nothing happens when you do step 3, but you do not give me much details to work with.
![image](https://user-images.githubusercontent.com/12627375/36544085-d8ce8b2c-17e5-11e8-84ca-cdbb924d103a.png)
After:
![image](https://user-images.githubusercontent.com/12627375/36544176-1efb2b82-17e6-11e8-859a-40f0aa5edeb3.png)

If you forgot step 2 you should see a error message like this:
![image](https://user-images.githubusercontent.com/12627375/36544849-c13c65e0-17e7-11e8-9112-258e04e1671b.png)

**Comment by reapsonex** [comment]
not included in save present

**Comment by Stekeblad** [comment]
I am really confused, I can not replicate your problem.
It even works when I try with a bunch of Greek, Russian and Arabic characters + other symbols as preset name.

Can you record a short video showing what you do for it to not work? Can you give more details in another way? Else I have no clue what's wrong and I will close the issue.

**Comment by reapsonex** [comment]
okey record videos !

**Comment by Stekeblad** [comment]
User opened a new issue and posted a video there #2
