### ISSUE TITLE
Quota

### ISSUE THREAD

**Issue by TodesAnge1** [Stekeblad/Stekeblads-Video-Uploader#19]
What is the quota for uploading videos through your api? A couple of days ago I was able to upload only 4 videos, but today more than 30 have uploaded without problems

**Comment by Stekeblad** [comment]
Hi @TodesAnge1,

There is a shared quota limit for all users of Stekeblads Video Uploader but no limit for individual users. I am observing a rapid growth in usage and keeping a close look on the quota usage reports from YouTube. The current limit have been reached several times during the last week and I have sent a request to YouTube for an increased limit that is currently under review. I can't promise when they reply but the last few times they have been pretty quick. Its christmas next week but I hope to have it approved before that.

I hope you will keep using Stekeblads Video Upload despite currently having to fight over the available quota.

**Comment by TodesAnge1** [comment]
I understand. My question is, how much is your daily limit now?

**Comment by Stekeblad** [comment]
Sorry, but I do not see the daily quota as a number I should throw around publicly,

**Comment by TodesAnge1** [comment]
Then, it's ok) Thanks for u reply

**Comment by TodesAnge1** [comment]
I've got one more question. Could you add support for managing multiple accounts at once? I just have 4 channels and I have to clean the files in .auth every time, and reconnect to your program, it's very long. I would be very grateful to you

**Comment by Stekeblad** [comment]
There is currently no plans for adding direct support for multiple channels, but it may happen in the future. The recommendation to users with multiple channels is to have one copy of Stekeblads Video Upload for each channel, all of them in different directories. Because settings, playlists, presets etc. is stored in the same directory as the program it will not interfere with another copy somewhere else on your computer.
