### ISSUE TITLE
After clicking on the get categories button, the following error appears:

### ISSUE THREAD

**Issue by aimbattt** [Stekeblad/Stekeblads-Video-Uploader#32]
After clicking on the get categories button, the following error appears:
The connection attempt failed.
Failed to establish connection to server localhost: 7835
error - https://i.imgur.com/eqlNPPE.png

**Comment by Stekeblad** [comment]
Hi @aimbattt 
It can be that something else on your computer is using that port (I will look into finding a random free port instead of a fixed one) or that something blocks the program from opening a port. This involves some of the oldest code in the program and its bad in handling and reporting errors that occur. I am working on improvements in that area but have not found much time lately.

**Comment by Stekeblad** [comment]
Hi @aimbattt 

I published version 1.4.6 a few hours ago that changes to use a random port
