### ISSUE TITLE
why does this exist

### ISSUE THREAD

**Issue by VRJacky** [Stekeblad/Stekeblads-Video-Uploader#61]
youtube HAS a schedule upload feature, the only point this program serves is to maliciously upload to channels that you do not own, the fact the "developer" has doubled down saying "aint my problem" instead of changing the way this program works or requiring some form of verification is so inappropriate

**Comment by Stekeblad** [comment]
Hi @VRJacky 

You have misunderstood how it works, Stekeblad's Video Uploader does not and can not give itself access to a channel. A user must convince Google they have permission to access a channel.

In slightly more technical and detailed explanation: Upon requesting authentication the YouTube API client launches the user's browser to a Google page and after a user has successfully authenticated with Google they can then tell Google to create an access token that is passed back to Stekeblad's Video Uploader. Google then only accepts that token in combination with the channel it was created for, it can not be used with other channels. When Stekeblad's Video Uploader receives a valid token from Google it should not need to worry about who the user is as by returning a token Google says that everything is fine and the user has the required permissions.

The code handling authentication is, to the best of my knowledge, following the recommendations from Google on how programs interacting with their APIs should do authentication.

Instead of blaming Stekeblad's Video Uploader for uploading content to your channel you could:
a) Blame Google for believing someone else when they claim to be you.
b) Blame YouTube for not recognising the video as something violating their terms and deleting it before it got published.
c) Blame yourself for not protecting your account/computer properly and enabling someone else to log in without your permission.

If Google and YouTube can't detect and stop attempts of malicious uploads, what do you think I can do to stop it? If I could come up with something I would be able to sell that algorithm and earn millions, while the bad guys just find another program or upload directly to YouTube.

I could also point out that scheduling when a video will be published is currently not a feature of Stekeblad's Video Uploader (but a feature to set this publish time on YouTube has been requested) however as that is not the main point of your issue I won't write more about that topic.
